### ISSUE TITLE
yarn install not work 

### ISSUE THREAD

**Issue by Pilotkosinus** [app-clones/netflix-clone#455]
I am trying to follow your instructions. I already have a problem with the first step. When i enter yarn install it doesn't find any file with the name install. i went into the order i clonetted with cd before. in your repository i couldn't find any file with the name install either. 

sorry i know the error is on me. i am stupid

**Comment by Pilotkosinus** [comment]
npm istall work. idk why yarn not work

**Comment by Beatzoid** [comment]
Did you do the following?
```
git clone https://github.com/app-clones/netflix-clone
cd netflix-clone
yarn install
```
If so, make sure you have yarn installed (`npm i -g yarn`), and if the issue still persists can you please post a screenshot of the error?

**Comment by Pilotkosinus** [comment]
has helped. thank you.

**Comment by Beatzoid** [comment]
No problem!
