### ISSUE TITLE
How to change the video for each movie

### ISSUE THREAD

**Issue by RAZ321** [app-clones/netflix-clone#475]
I used the netflix clone that you created but I don't know how to put a different video for each film because it's always the bunny.mp4 that is play, thank.

**Comment by Beatzoid** [comment]
That is not a current feature of the project, and unfortunately, I have a lot going on in my life right now, so I don't have time to add that feature. If you want to submit a PR, I will gladly review it and give you feedback.

**Comment by RAZ321** [comment]
Pleeaaase

**Comment by Beatzoid** [comment]
Good news, @RAZ321! I have started a rewrite of the project inside the [rewrite](https://github.com/app-clones/netflix-clone/tree/rewrite) branch of this repository, and it has the functionality you're asking for! It should hopefully be done within the next couple of weeks

**Comment by RAZ321** [comment]
is there anything new?

**Comment by Beatzoid** [comment]
Bump, been busy sorry
